title: Spring 2020 Development Blog
author: Nathan Bailey
email: dbailey@k12k.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is an example for students of how to blog as a developer. I will blog about some of the things I develop this Spring.

# social links
twitter_username: tribebytes # DO NOT include the @ character, or else the build will fail!
github_username:  dnbailey # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

remote_theme: minicomp/ed
